version: "3.9"
name: gque
services:
    gque:
        container_name: "gque"
        image: gque
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            # <<local host port >>:<<container port>>
            - 5456:5456
        environment:
            PORT: 5456
