version: "3.9"
name: gque-local
services:
    gnosql:
        container_name: "gnosql"
        image: nanda03dev/gnosql:latest
        ports:
            # <<local host port >>:<<container port>>
            - 5454:5454
            - 5455:5455
        volumes:
            - gnosqldb-data:/root/gnosql/db/
        environment:
            GIN_PORT: 5454
            GRPC_PORT: 5455
    gque:
        container_name: "gque-local"
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
            # <<local host port >>:<<container port>>
            - 5456:5456
        environment:
            # Gque server run at 5456
            GQUE_PORT: 5456
            GNOSQL_SERVER: gnosql:5455
        depends_on:
            - gnosql        
volumes:
    gnosqldb-data:
        name: gnosqldb-data
